### ISSUE TITLE
Error: Uncaught (in promise): ClientAuthError: Token renewal operation failed due to timeout.

### ISSUE THREAD

**Issue by rprasath** [Azure-Samples/active-directory-b2c-javascript-angular-spa#25]
I downloading and ran this sample without making any changes and logged-in with google social login. When I hit call API I am getting the below error.

core.js:6241 ERROR Error: Uncaught (in promise): ClientAuthError: Token renewal operation failed due to timeout.
ClientAuthError: Token renewal operation failed due to timeout.
    at ClientAuthError.AuthError [as constructor] (AuthError.ts:26)
    at new ClientAuthError (ClientAuthError.ts:108)
    at Function.ClientAuthError.createTokenRenewalTimeoutError (ClientAuthError.ts:141)
    at WindowUtils.ts:65
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:503)
    at ZoneTask.invoke (zone.js:492)
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.invokeTask (zone.js:507)
    at ZoneTask.invoke (zone.js:492)

![image](https://user-images.githubusercontent.com/4444661/95129076-72244d00-0728-11eb-8da9-95e826d6cd23.png)

I am getting the same error with my application as well

**Comment by derisen** [comment]
@rprasath is it the case that IdP's other than Google work fine i.e. the issue is with Google social login? 

Also, can you update the msal package to 1.4.1? There was a known issue that is likely solved by the latest version.

**Comment by derisen** [comment]
@rprasath did that help with your issue?

**Comment by rprasath** [comment]
@derisen No it didn't fix. 

I am using @azure/msal-angular 1.1.1 and msal 1.4.1. Stil the same error.

**Comment by derisen** [comment]
@rprasath can you share your configuration parameters? Also, a network trace would help here: you can use [Fiddler](https://www.telerik.com/fiddler) for that. You can send these files to me over email using the email address on my profile.

**Comment by derisen** [comment]
@rprasath also, does this only occur when trying to sign-in with Google social login or is it in general?

**Comment by vincentlecours** [comment]
Same thing here with Facebook as a provider

**Comment by derisen** [comment]
@vincentlecours this seems to be a known issue being [tracked here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1934). What version of the library are you using? If you haven't already, would update your `msal` and `msal-angular` packages?

**Comment by vincentlecours** [comment]
@derisen I was able to make it work by setting my site as an exception for Tracking Prevention in Edge. After adding the url, everything seemed to be working as expected. Before doing that, I had warnings in the console saying that the facebook login url was unable to access my storage because of tracking prevention

**Comment by derisen** [comment]
aha, glad you resolved your issue 👍

**Comment by vincentlecours** [comment]
Well, I wouldn't call that resolved as I can't ask people to remove tracking protection or add my site to the exceptions before visiting my site, but now I know that the issue is related to that and the issue you mentioned is exactly what I'm experiencing so thanks for that. I'll follow this for more info!

**Comment by foramkumar-parekh** [comment]
This issue is here for more than a few weeks now. Do you have any fix or workaround as of now?

Putting URL in the exception list or removing tracking is not something I can recommend to application users.

@derisen we would really like to have a fix to this issue as soon as possible.

**Comment by vincentlecours** [comment]
The way I resolved my issue is by upgrading manually to msal.js 2.0. So far, everything seems to work as expected with the new version. Hope this helps!

**Comment by derisen** [comment]
@foramkumar-parekh unfortunately, the issue is still [being tracked](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1934).  If you would like to give a try to msal.js 2.x version, you can find it [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample).

**Comment by foramkumar-parekh** [comment]
> The way I resolved my issue is by upgrading manually to msal.js 2.0. So far, everything seems to work as expected with the new version. Hope this helps!

I am using @azure/msal-angular along with msal.js. On npm, I can see the latest version of msal.js as 1.4.2. 
A couple of questions:

- how can I get V2 of msal.js, if latest on npm is 1.4?
- What about the compatibility of msal.js@V2 with @azure/msal-angular@1.1.1?

**Comment by derisen** [comment]
@foramkumar-parekh sorry for the confusion. So MSAL.js has two major versions 1.x (using implicit flow) and 2.x (using auth code flow). MSAL-Angular library is based on MSAL.js 1.x.

The angular sample I've link is using MSAL.js 2.x **directly**, without using a wrapper library like MSAL-Angular. MSAL-Angular is being updated at the moment to use the 2.x, but it's not ready yet (see here the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md) for ETAs).

Hope this helps.

**Comment by derisen** [comment]
@foramkumar-parekh @vincentlecours The issue should have been resolved by now. Closing, please open a new ticket if this is not resolved after upgrading.

Also, a new B2C sample using msal-angular-v2 with auth code is now [available here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-angular-v2/samples/msal-angular-v2-samples/angular11-b2c-sample).

**Comment by rnkpareek** [comment]
> @foramkumar-parekh @vincentlecours The issue should have been resolved by now. Closing, please open a new ticket if this is not resolved after upgrading.
> 
> Also, a new B2C sample using msal-angular-v2 with auth code is now [available here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-angular-v2/samples/msal-angular-v2-samples/angular11-b2c-sample).
404 iws
